name: Docker Image CI

on:
  push:

env:
  TEST_TAG: drvdijk/rclone-sync:test

jobs:
  build:
    name: Build docker-rclone-sync image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: hadolint/hadolint-action@v3.1.0
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Show version
        run: |
          docker run --rm ${{ env.TEST_TAG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TEST_TAG }}
